---

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
name:		 "DeeZ"
title:       "DeeZ: reference-based compression by local assembly"
keywords:    "deez, compression, sam, bam, nature methods, local assembly"
description: "A tool for compressing SAM/BAM files"
source_link: "http://sfu-compbio.github.io/deez/"
