---

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
name:		 "DeeZ"
title:       "DeeZ: reference-based compression by local assembly"
keywords:    "deez, compression, sam, bam, samtools, nature methods"
description: "A tool for compressing SAM/BAM files"
source_link: "http://sfu-compbio.github.io/deez/"
